// src/data/baseTrainings.ts

import type { Training } from '../types';

export const baseTrainings: Training[] = [
  {
    id: 'tr_hand_safety',
    title: 'Cuidado de Manos',
    description: 'Capacitación sobre prevención de lesiones y cuidado de manos en tareas operativas.',
    category: 'HSE',
    duration_minutes: 8,
    validity_months: 12,
    certificate_enabled: true,
    passing_score: 70,
    max_attempts: 3,
    status: 'active',
    created_at: new Date().toISOString(),
    module_count: 1,
    tenant_count: 0,
  },
  {
    id: 'tr_working_at_heights',
    title: 'Trabajo en Altura',
    description: 'Buenas prácticas y reglas básicas para trabajos en altura.',
    category: 'Seguridad',
    duration_minutes: 10,
    validity_months: 12,
    certificate_enabled: true,
    passing_score: 70,
    max_attempts: 3,
    status: 'active',
    created_at: new Date().toISOString(),
    module_count: 1,
    tenant_count: 0,
  },
  {
    id: 'tr_confined_spaces',
    title: 'Espacios Confinados',
    description: 'Riesgos, permisos y controles básicos para tareas en espacios confinados.',
    category: 'HSE',
    duration_minutes: 10,
    validity_months: 12,
    certificate_enabled: true,
    passing_score: 70,
    max_attempts: 3,
    status: 'active',
    created_at: new Date().toISOString(),
    module_count: 1,
    tenant_count: 0,
  },
  {
    id: 'tr_energy_isolation',
    title: 'Aislamiento de Energía',
    description: 'Bloqueo, etiquetado y control de energías peligrosas.',
    category: 'Seguridad',
    duration_minutes: 10,
    validity_months: 12,
    certificate_enabled: true,
    passing_score: 70,
    max_attempts: 3,
    status: 'active',
    created_at: new Date().toISOString(),
    module_count: 1,
    tenant_count: 0,
  },
  {
    id: 'tr_line_of_fire',
    title: 'Línea de Fuego',
    description: 'Identificación y prevención de exposición a movimientos o energías peligrosas.',
    category: 'Seguridad',
    duration_minutes: 10,
    validity_months: 12,
    certificate_enabled: true,
    passing_score: 70,
    max_attempts: 3,
    status: 'active',
    created_at: new Date().toISOString(),
    module_count: 1,
    tenant_count: 0,
  },
  {
    id: 'tr_mechanical_lifting',
    title: 'Izaje Mecánico Seguro',
    description: 'Conceptos básicos para operaciones de izaje y cargas suspendidas.',
    category: 'HSE',
    duration_minutes: 10,
    validity_months: 12,
    certificate_enabled: true,
    passing_score: 70,
    max_attempts: 3,
    status: 'active',
    created_at: new Date().toISOString(),
    module_count: 1,
    tenant_count: 0,
  },
  {
    id: 'tr_hot_work',
    title: 'Trabajo en Caliente',
    description: 'Prevención de incidentes en tareas con calor, chispas o llama abierta.',
    category: 'HSE',
    duration_minutes: 10,
    validity_months: 12,
    certificate_enabled: true,
    passing_score: 70,
    max_attempts: 3,
    status: 'active',
    created_at: new Date().toISOString(),
    module_count: 1,
    tenant_count: 0,
  },
  {
    id: 'tr_code_of_ethics',
    title: 'Código de Ética',
    description: 'Lectura y aceptación del código de ética y conducta de la empresa.',
    category: 'Compliance',
    duration_minutes: 5,
    validity_months: 12,
    certificate_enabled: false,
    passing_score: 0,
    max_attempts: null,
    status: 'active',
    created_at: new Date().toISOString(),
    module_count: 1,
    tenant_count: 0,
  },
];
